spring:
    datasource:
      url: jdbc:h2:tcp://localhost/~/agoraboard
      # jdbc:h2:~/agoraboard
      # jdbc:h2:tcp://localhost/~/agoraboard
      # jdbc:h2:mem:agora;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
      username: sa
      password:
      driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true

logging.level:
  org.hibernate.SQL: debug